import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "@supabase/supabase-js";
import postgres from "postgres";

const SUPABASE_URL=Deno.env.get("SUPABASE_URL"),SERVICE_ROLE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"),DATABASE_URL=Deno.env.get("SUPABASE_DB_URL");
const APP_ORIGIN="https://drmacze.github.io",VERSION="jobs-v5.3.0";
if(!SUPABASE_URL||!SERVICE_ROLE_KEY||!DATABASE_URL)throw new Error("BACKEND_ENVIRONMENT_INCOMPLETE");
const authAdmin=createClient(SUPABASE_URL,SERVICE_ROLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const sql=postgres(DATABASE_URL,{prepare:false,max:3,idle_timeout:20,connect_timeout:10});
const encoder=new TextEncoder();
const allowedOrigins=new Set([APP_ORIGIN,"http://localhost:3000","http://localhost:4173","http://127.0.0.1:3000","http://127.0.0.1:4173"]);
const uuidPattern=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const domainPattern=/^(?=.{1,253}$)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/i;
const ipv4Pattern=/^(25[0-5]|2[0-4]\d|1?\d?\d)(\.(25[0-5]|2[0-4]\d|1?\d?\d)){3}$/;
class ApiError extends Error{constructor(code,status=400,message="",retryable=false,details={}){super(message||code);this.code=code;this.status=status;this.retryable=retryable;this.details=details}}
const clean=(value,max=300)=>String(value??"").replace(/[<>]/g,"").trim().slice(0,max);
async function sha256(value){const digest=await crypto.subtle.digest("SHA-256",encoder.encode(String(value)));return[...new Uint8Array(digest)].map(byte=>byte.toString(16).padStart(2,"0")).join("")}
function decodeClaims(token){try{const part=token.split(".")[1],normalized=part.replace(/-/g,"+").replace(/_/g,"/").padEnd(Math.ceil(part.length/4)*4,"=");return JSON.parse(atob(normalized))}catch{return{}}}
function isPublicIPv4(ip){if(!ipv4Pattern.test(ip))return false;const[a,b]=ip.split(".").map(Number);return !(a===0||a===10||a===127||(a===169&&b===254)||(a===172&&b>=16&&b<=31)||(a===192&&b===168)||a>=224)}
function normalizeDomain(value){return clean(value,253).toLowerCase().replace(/^https?:\/\//,"").replace(/\/.*$/,"").replace(/\.$/,"")}
function cors(req){const origin=req.headers.get("origin")||"",allowed=!origin||allowedOrigins.has(origin);return{allowed,headers:{"Access-Control-Allow-Origin":origin&&allowed?origin:APP_ORIGIN,"Vary":"Origin","Access-Control-Allow-Headers":"authorization, apikey, content-type, x-device-id, x-device-label, x-device-platform, x-device-browser, x-idempotency-key, x-client-version","Access-Control-Allow-Methods":"POST, OPTIONS","Access-Control-Max-Age":"86400"}}}
function reply(req,requestId,body,status=200){return new Response(JSON.stringify({ok:status<400,request_id:requestId,backend_version:VERSION,...body},(_key,value)=>typeof value==="bigint"?String(value):value),{status,headers:{...cors(req).headers,"Content-Type":"application/json","Cache-Control":"no-store","X-Request-ID":requestId,"X-CYBERTRMX-Backend":VERSION}})}
function fail(req,requestId,error){const known=error instanceof ApiError;return reply(req,requestId,{error:known?error.code:"INTERNAL_ERROR",message:known?error.message:"The job API could not complete this request.",retryable:known?error.retryable:false,details:known?error.details:{}},known?error.status:500)}
const browserFamily=ua=>/CriOS|Chrome/i.test(ua)?"Chrome":/FxiOS|Firefox/i.test(ua)?"Firefox":/EdgiOS|Edg/i.test(ua)?"Edge":/Safari/i.test(ua)?"Safari":"Browser";
const platformFamily=ua=>/iPhone/i.test(ua)?"iPhone":/iPad/i.test(ua)?"iPad":/Android/i.test(ua)?"Android":/Macintosh|Mac OS/i.test(ua)?"macOS":/Windows/i.test(ua)?"Windows":/Linux/i.test(ua)?"Linux":"Unknown platform";
const requestIp=req=>clean(req.headers.get("cf-connecting-ip")||req.headers.get("x-real-ip")||(req.headers.get("x-forwarded-for")||"").split(",")[0],80);
async function identity(req){const token=(req.headers.get("Authorization")||"").replace(/^Bearer\s+/i,"");if(!token)throw new ApiError("AUTH_REQUIRED",401,"Sign in before using the job queue.");const{data,error}=await authAdmin.auth.getUser(token);if(error||!data.user)throw new ApiError("AUTH_INVALID",401,"Your session is no longer valid. Sign in again.");const claims=decodeClaims(token);return{user:data.user,sessionId:uuidPattern.test(claims.session_id||"")?claims.session_id:null,aal:claims.aal||"aal1"}}
async function workspace(userId,requested){if(requested&&!uuidPattern.test(requested))throw new ApiError("WORKSPACE_ID_INVALID",400,"The workspace identifier is invalid.");const rows=requested?await sql`select wm.workspace_id,wm.role from public.workspace_members wm where wm.user_id=${userId}::uuid and wm.workspace_id=${requested}::uuid limit 1`:await sql`select wm.workspace_id,wm.role from public.workspace_members wm where wm.user_id=${userId}::uuid order by wm.created_at limit 1`;if(!rows.length)throw new ApiError("WORKSPACE_ACCESS_DENIED",403,"This account does not have workspace access.");return{id:rows[0].workspace_id,role:rows[0].role}}
async function rateLimit(scope,key,limit,seconds){const rows=await sql`select allowed,remaining,reset_at from public.consume_rate_limit(${await sha256(`${scope}:${key}`)},${limit},${seconds})`;if(!rows[0]?.allowed)throw new ApiError("RATE_LIMITED",429,"Too many job requests were received.",true,{reset_at:rows[0]?.reset_at||null})}
async function ensureDevice(req,id,access){const deviceId=clean(req.headers.get("x-device-id"),64);if(!uuidPattern.test(deviceId))throw new ApiError("DEVICE_ID_REQUIRED",400,"This browser could not establish a device identity.");const ua=clean(req.headers.get("user-agent"),500),label=clean(req.headers.get("x-device-label"),80)||`${platformFamily(ua)} · ${browserFamily(ua)}`,platform=clean(req.headers.get("x-device-platform"),80)||platformFamily(ua),browser=clean(req.headers.get("x-device-browser"),80)||browserFamily(ua),uaHash=await sha256(ua||"unknown"),ipHash=await sha256(requestIp(req)||"unknown");if(id.sessionId){const bound=await sql`select device_id from public.user_devices where user_id=${id.user.id}::uuid and session_id=${id.sessionId}::uuid and revoked_at is null limit 1`;if(bound.length&&String(bound[0].device_id)!==deviceId)throw new ApiError("SESSION_DEVICE_MISMATCH",403,"This session is bound to another device identity.")}
const existing=await sql`select revoked_at from public.user_devices where user_id=${id.user.id}::uuid and device_id=${deviceId}::uuid limit 1`;if(existing[0]?.revoked_at)throw new ApiError("DEVICE_REVOKED",403,"Access from this device has been revoked.");try{await sql`insert into public.user_devices(user_id,workspace_id,device_id,session_id,label,platform,browser,user_agent_hash,last_ip_hash,last_seen_at,metadata) values (${id.user.id}::uuid,${access.id}::uuid,${deviceId}::uuid,${id.sessionId}::uuid,${label},${platform},${browser},${uaHash},${ipHash},now(),${JSON.stringify({client_version:clean(req.headers.get("x-client-version"),40)})}::jsonb) on conflict (user_id,device_id) do update set workspace_id=excluded.workspace_id,session_id=excluded.session_id,platform=excluded.platform,browser=excluded.browser,user_agent_hash=excluded.user_agent_hash,last_ip_hash=excluded.last_ip_hash,last_seen_at=now(),metadata=public.user_devices.metadata||excluded.metadata`}catch(error){if(String(error?.message||"").includes("idx_user_devices_session"))throw new ApiError("SESSION_DEVICE_MISMATCH",403,"This session is bound to another device identity.");throw error}return deviceId}
async function enforceMfa(id){const rows=await sql`select exists(select 1 from auth.mfa_factors where user_id=${id.user.id}::uuid and status='verified') as enabled`;if(rows[0]?.enabled&&id.aal!=="aal2")throw new ApiError("MFA_REQUIRED",403,"Verify your authenticator code before continuing.")}
async function requireCase(workspaceId,raw){const value=clean(raw,64);if(!value)return null;if(!uuidPattern.test(value))throw new ApiError("CASE_ID_INVALID",400,"The case identifier is invalid.");const rows=await sql`select id from public.cases where id=${value}::uuid and workspace_id=${workspaceId}::uuid limit 1`;if(!rows.length)throw new ApiError("CASE_NOT_FOUND",404,"The selected case was not found in this workspace.");return value}
async function audit(context,action,resourceId,details={}){await sql`insert into public.audit_log(workspace_id,actor_id,action,resource_type,resource_id,details) values (${context.workspaceId}::uuid,${context.userId}::uuid,${action},'job',${resourceId},${JSON.stringify({...details,request_id:context.requestId,device_id:context.deviceId})}::jsonb)`}
async function kick(source){try{await sql`select private.kick_cybertrmx_worker(${source})`}catch(error){console.error("CYBERTRMX_JOB_KICK",error?.message||error)}}

Deno.serve(async req=>{const requestId=crypto.randomUUID(),origin=cors(req);if(req.method==="OPTIONS")return new Response("ok",{headers:origin.headers});if(!origin.allowed)return fail(req,requestId,new ApiError("ORIGIN_NOT_ALLOWED",403,"This request origin is not allowed."));if(req.method!=="POST")return fail(req,requestId,new ApiError("METHOD_NOT_ALLOWED",405,"Use POST for this endpoint."));let context=null;try{const id=await identity(req),payload=await req.json().catch(()=>({})),action=clean(payload.action,60),access=await workspace(id.user.id,clean(payload.workspace_id,64)||undefined),deviceId=await ensureDevice(req,id,access);await enforceMfa(id);context={requestId,workspaceId:access.id,userId:id.user.id,deviceId};await rateLimit("jobs-user",id.user.id,120,300);await rateLimit("jobs-device",deviceId,100,300);
if(action==="run_lookup"){
  await rateLimit("jobs-enqueue",id.user.id,20,300);
  const type=clean(payload.job_type,40),input=clean(payload.input,253),queueKey=clean(req.headers.get("x-idempotency-key")||payload.idempotency_key,100)||requestId;
  if(!["dns_inventory","rdap_lookup","ip_enrichment"].includes(type))throw new ApiError("JOB_TYPE_NOT_SUPPORTED",400,"That collection job is not available.");
  if(!input)throw new ApiError("LOOKUP_INPUT_REQUIRED",400,"Enter a domain or public IP address.");
  if(type==="dns_inventory"&&!domainPattern.test(normalizeDomain(input)))throw new ApiError("DOMAIN_FORMAT_INVALID",400,"Enter a valid domain name.");
  if(type==="ip_enrichment"&&!isPublicIPv4(input))throw new ApiError("PUBLIC_IPV4_REQUIRED",400,"Enter a public IPv4 address.");
  if(type==="rdap_lookup"&&!domainPattern.test(normalizeDomain(input))&&!isPublicIPv4(input))throw new ApiError("RDAP_INPUT_INVALID",400,"Enter a valid domain or public IPv4 address.");
  const caseId=await requireCase(access.id,payload.case_id),scopeId=clean(payload.scope_asset_id,64)||null;
  if(scopeId){if(!uuidPattern.test(scopeId))throw new ApiError("SCOPE_ID_INVALID",400,"The scope identifier is invalid.");const scoped=await sql`select id from public.scope_assets where id=${scopeId}::uuid and workspace_id=${access.id}::uuid limit 1`;if(!scoped.length)throw new ApiError("SCOPE_NOT_FOUND",404,"The requested scope entry was not found.")}
  const inserted=await sql`insert into public.jobs(workspace_id,case_id,scope_asset_id,job_type,status,progress,created_by,request_payload,queue_key,priority,max_attempts,timeout_seconds,available_at) values (${access.id}::uuid,${caseId}::uuid,${scopeId}::uuid,${type},'queued',0,${id.user.id}::uuid,${JSON.stringify({input,source:"operations-v5.3"})}::jsonb,${queueKey},${Math.max(-100,Math.min(100,Number(payload.priority)||0))},${Math.max(1,Math.min(5,Number(payload.max_attempts)||3))},${Math.max(10,Math.min(180,Number(payload.timeout_seconds)||45))},now()) on conflict (created_by,queue_key) where queue_key is not null do nothing returning *`;
  const rows=inserted.length?inserted:await sql`select * from public.jobs where created_by=${id.user.id}::uuid and queue_key=${queueKey} limit 1`,job=rows[0];
  if(inserted.length){await sql`select private.append_job_event(${job.id}::uuid,'QUEUED','Job accepted by the persistent queue',0,'info',${JSON.stringify({input,request_id:requestId})}::jsonb)`;await audit(context,"job.queued",String(job.id),{job_type:type,input,max_attempts:job.max_attempts,timeout_seconds:job.timeout_seconds});await kick("enqueue")}
  return reply(req,requestId,{job_id:job.id,status:job.status,job,idempotent_replay:!inserted.length,poll_after_ms:2000},inserted.length?202:200);
}
if(action==="job_status"){
  await rateLimit("jobs-status",id.user.id,180,60);const jobId=clean(payload.job_id,64);if(!uuidPattern.test(jobId))throw new ApiError("JOB_ID_INVALID",400,"The job identifier is invalid.");
  const jobs=await sql`select * from public.jobs where id=${jobId}::uuid and workspace_id=${access.id}::uuid limit 1`;if(!jobs.length)throw new ApiError("JOB_NOT_FOUND",404,"The requested job was not found.");
  const events=await sql`select * from public.job_events where job_id=${jobId}::uuid order by sequence`;
  return reply(req,requestId,{job:jobs[0],events,poll_after_ms:["queued","running","retry_wait","validating"].includes(jobs[0].status)?2000:10000});
}
if(action==="cancel_job"){
  await rateLimit("jobs-cancel",id.user.id,30,3600);const jobId=clean(payload.job_id,64);if(!uuidPattern.test(jobId))throw new ApiError("JOB_ID_INVALID",400,"The job identifier is invalid.");
  const jobs=await sql`select * from public.jobs where id=${jobId}::uuid and workspace_id=${access.id}::uuid for update`;if(!jobs.length)throw new ApiError("JOB_NOT_FOUND",404,"The requested job was not found.");const job=jobs[0];
  if(["completed","failed","timed_out","cancelled","dead_letter"].includes(job.status))return reply(req,requestId,{job,already_terminal:true});
  if(["queued","retry_wait","validating"].includes(job.status)){await sql`update public.jobs set cancel_requested_at=now(),status='cancelled',cancelled_at=now(),finished_at=now(),worker_id=null,lease_expires_at=null where id=${jobId}::uuid`;await sql`select private.append_job_event(${jobId}::uuid,'CANCELLED','Job cancelled before provider execution',${job.progress},'warning','{}'::jsonb)`}else{await sql`update public.jobs set cancel_requested_at=coalesce(cancel_requested_at,now()) where id=${jobId}::uuid`;await sql`select private.append_job_event(${jobId}::uuid,'CANCEL_REQUESTED','Worker will stop at the next cancellation checkpoint',${job.progress},'warning','{}'::jsonb)`;await kick("cancel")}
  await audit(context,"job.cancel_requested",jobId,{previous_status:job.status});const updated=await sql`select * from public.jobs where id=${jobId}::uuid`;return reply(req,requestId,{job:updated[0]});
}
if(action==="retry_job"){
  await rateLimit("jobs-retry",id.user.id,20,3600);const sourceId=clean(payload.job_id,64),queueKey=clean(req.headers.get("x-idempotency-key")||payload.idempotency_key,100)||requestId;if(!uuidPattern.test(sourceId))throw new ApiError("JOB_ID_INVALID",400,"The job identifier is invalid.");
  const sources=await sql`select * from public.jobs where id=${sourceId}::uuid and workspace_id=${access.id}::uuid limit 1`;if(!sources.length)throw new ApiError("JOB_NOT_FOUND",404,"The requested job was not found.");const source=sources[0];
  if(!["failed","timed_out","cancelled","dead_letter"].includes(source.status))throw new ApiError("JOB_RETRY_NOT_ALLOWED",409,"Only failed, timed out, cancelled, or dead-letter jobs can be retried.");
  if(!source.request_payload?.input)throw new ApiError("JOB_INPUT_UNAVAILABLE",409,"The original job predates the persistent queue and cannot be retried automatically.");
  const inserted=await sql`insert into public.jobs(workspace_id,case_id,scope_asset_id,job_type,status,progress,created_by,request_payload,queue_key,priority,max_attempts,timeout_seconds,available_at,retry_of_job_id) values (${access.id}::uuid,${source.case_id}::uuid,${source.scope_asset_id}::uuid,${source.job_type},'queued',0,${id.user.id}::uuid,${JSON.stringify(source.request_payload)}::jsonb,${queueKey},${source.priority},${source.max_attempts},${source.timeout_seconds},now(),${source.id}::uuid) on conflict (created_by,queue_key) where queue_key is not null do nothing returning *`;
  const rows=inserted.length?inserted:await sql`select * from public.jobs where created_by=${id.user.id}::uuid and queue_key=${queueKey} limit 1`,job=rows[0];
  if(inserted.length){await sql`select private.append_job_event(${job.id}::uuid,'QUEUED','Manual retry accepted by the persistent queue',0,'info',${JSON.stringify({retry_of_job_id:source.id})}::jsonb)`;await audit(context,"job.manual_retry",String(job.id),{retry_of_job_id:source.id});await kick("manual-retry")}
  return reply(req,requestId,{job_id:job.id,status:job.status,job,idempotent_replay:!inserted.length,poll_after_ms:2000},inserted.length?202:200);
}
if(action==="queue_status"){
  const jobs=await sql`select * from public.jobs where workspace_id=${access.id}::uuid order by created_at desc limit 60`;
  const counts=await sql`select status,count(*)::integer as count from public.jobs where workspace_id=${access.id}::uuid group by status order by status`;
  return reply(req,requestId,{jobs,counts,server_time:new Date().toISOString(),poll_after_ms:5000});
}
throw new ApiError("ACTION_NOT_SUPPORTED",400,"That job action is not supported.");
}catch(error){console.error("CYBERTRMX_JOBS",requestId,error?.code||"INTERNAL",error?.message||error);return fail(req,requestId,error)}});
